/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Statistics */

#ifndef _Included_Statistics
#define _Included_Statistics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Statistics
 * Method:    sum
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Statistics_sum
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     Statistics
 * Method:    avg
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Statistics_avg
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     Statistics
 * Method:    stddev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Statistics_stddev
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
